services:
  db1:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
    ports: ["5433:5432"]

  db2:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
    ports: ["5434:5432"]

  pgpool:
    image: bitnami/pgpool:latest
    environment:
      PGPOOL_BACKEND_NODES: "0:db1:5432,1:db2:5432"
      PGPOOL_SR_CHECK_USER: postgres
      PGPOOL_SR_CHECK_PASSWORD: example
      PGPOOL_POSTGRES_PASSWORD: example
    ports: ["5432:5432"]
    depends_on: [db1, db2]

