# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: insurance_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 0, "", "insurance_service.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17insurance_service.proto\x12\tinsurance"-\n\x10InsuranceRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02"0\n\x11InsuranceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t">\n\rInsuranceData\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x12\n\ncreated_at\x18\x03 \x01(\t"\x07\n\x05\x45mpty"=\n\rInsuranceList\x12,\n\ninsurances\x18\x01 \x03(\x0b\x32\x18.insurance.InsuranceData2\xa2\x01\n\x10InsuranceService\x12N\n\x11RegisterInsurance\x12\x1b.insurance.InsuranceRequest\x1a\x1c.insurance.InsuranceResponse\x12>\n\x10GetAllInsurances\x12\x10.insurance.Empty\x1a\x18.insurance.InsuranceListb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "insurance_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_INSURANCEREQUEST"]._serialized_start = 38
    _globals["_INSURANCEREQUEST"]._serialized_end = 83
    _globals["_INSURANCERESPONSE"]._serialized_start = 85
    _globals["_INSURANCERESPONSE"]._serialized_end = 133
    _globals["_INSURANCEDATA"]._serialized_start = 135
    _globals["_INSURANCEDATA"]._serialized_end = 197
    _globals["_EMPTY"]._serialized_start = 199
    _globals["_EMPTY"]._serialized_end = 206
    _globals["_INSURANCELIST"]._serialized_start = 208
    _globals["_INSURANCELIST"]._serialized_end = 269
    _globals["_INSURANCESERVICE"]._serialized_start = 272
    _globals["_INSURANCESERVICE"]._serialized_end = 434
# @@protoc_insertion_point(module_scope)
